added instructions, startup script and ssh key generation

diff --git a/provision/ansible/roles/sitm/templates/sitmd b/provision/ansible/roles/sitm/templates/sitmd
--- a/provision/ansible/roles/sitm/templates/sitmd
+++ b/provision/ansible/roles/sitm/templates/sitmd
@@ -12,21 +12,77 @@
 
 # @todo any command placed here will run unconditionally
 
-DAEMON="sitmd"
+SERVICE_NAME={{service_name}}
+DAEMON={{daemon}}
+DAEMON_OPTS="{{daemon_opts}}"
+PIDFILE={{pidfile}}
+
+if [ ! -x $DAEMON ]; then
+  echo "ERROR: Can't execute $DAEMON."
+  exit 1
+fi
+
+start_service() {
+  echo -n " * Starting $SERVICE_NAME... "
+  start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
+  e=$?
+  if [ $e -eq 1 ]; then
+    echo "already running"
+    return
+  fi
+
+  if [ $e -eq 255 ]; then
+    echo "couldn't start :("
+    exit 1
+  fi
+
+  echo "done"
+}
+
+stop_service() {
+  echo -n " * Stopping $SERVICE_NAME... "
+  start-stop-daemon -Kq -R 10 -p $PIDFILE
+  e=$?
+  if [ $e -eq 1 ]; then
+    echo "not running"
+    return
+  fi
+
+  echo "done"
+}
+
+status_service() {
+    printf "%-50s" "Checking $SERVICE_NAME..."
+    if [ -f $PIDFILE ]; then
+        PID=`cat $PIDFILE`
+        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
+            printf "%s\n" "Process dead but pidfile exists"
+            exit 1
+        else
+            echo "Running"
+        fi
+    else
+        printf "%s\n" "Service not running"
+        exit 3
+    fi
+}
 
 case "$1" in
+  status)
+    status_service
+    ;;
   start)
-    echo "Starting $DAEMON"
-    # run application you want to start
-    /usr/local/bin/sitmd
+    start_service
     ;;
   stop)
-    echo "Stopping $DAEMON"
-    # kill application you want to stop
-    killall sitmd
+    stop_service
+    ;;
+  restart)
+    stop_service
+    start_service
     ;;
   *)
-    echo "Usage: /etc/init.d/sitmd {start|stop}"
+    echo "Usage: service $SERVICE_NAME {start|stop|restart|status}" >&2
     exit 1
     ;;
 esac
